ERROR: %s %s %s
[10/10/2008 16:43:34] language
ERROR: GET /user/mru/preferences mru
[10/10/2008 16:43:34] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 106, in read
    create_platform_preferences(user) # Create all platform preferences for the user (if not exist)
  File "/home/juanjo/ezweb/preferences/views.py", line 100, in create_platform_preferences
    preference = Preference(user=user, selectedValue=preferenceDef_fields['defaultValue'], preferenceDef=preferenceDef_name)
  File "/var/lib/python-support/python2.5/django/db/models/base.py", line 253, in __init__
    setattr(self, field.name, rel_obj)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 264, in __set__
    self.field.name, self.field.rel.to._meta.object_name))
ValueError: Cannot assign "u'language'": "Preference.preferenceDef" must be a "PreferenceDef" instance.

ERROR: GET /user/mru/preferences mru
[10/10/2008 16:47:59] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 105, in read
    create_platform_preferences(user) # Create all platform preferences for the user (if not exist)
  File "/home/juanjo/ezweb/preferences/views.py", line 97, in create_platform_preferences
    preference = Preference.objects.get(user=user, preferenceDef=preferenceDef)
  File "/var/lib/python-support/python2.5/django/db/models/manager.py", line 93, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 298, in get
    num = len(clone)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 154, in __len__
    self._result_cache = list(self.iterator())
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 269, in iterator
    for row in self.query.results_iter():
  File "/var/lib/python-support/python2.5/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/lib/python-support/python2.5/django/db/models/sql/query.py", line 1700, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/python-support/python2.5/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/var/lib/python-support/python2.5/django/db/backends/mysql/base.py", line 83, in execute
    return self.cursor.execute(query, args)
  File "/var/lib/python-support/python2.5/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/var/lib/python-support/python2.5/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'pk\': "\'language\'", \'model\': "\'preferences.preferencedef\'", \'fields\': {\'defaultV\' at line 1')

ERROR: %s %s %s
[10/10/2008 16:52:25] language
ERROR: GET /user/mru/preferences mru
[10/10/2008 16:52:25] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 106, in read
    preferences = Preference.objects.filter(user=user)
  File "/home/juanjo/ezweb/preferences/views.py", line 98, in create_platform_preferences
    except Preference.DoesNotExist:
KeyError: 'name'

ERROR: %s %s %s
[10/10/2008 16:54:21] holita
ERROR: GET /user/mru/preferences mru
[10/10/2008 16:54:21] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 105, in read
    create_platform_preferences(user) # Create all platform preferences for the user (if not exist)
  File "/home/juanjo/ezweb/preferences/views.py", line 97, in create_platform_preferences
    preference = Preference.objects.get(user=user, preferenceDef=preferenceDef_obj)
KeyError: 'name'

ERROR: %s %s %s
[10/10/2008 17:06:13] holita
ERROR: GET /user/jlopez/preferences jlopez
[10/10/2008 17:06:13] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 105, in read
    create_platform_preferences(user) # Create all platform preferences for the user (if not exist)
  File "/home/juanjo/ezweb/preferences/views.py", line 97, in create_platform_preferences
    preference = Preference.objects.get(user=user, preferenceDef=preferenceDef['pk'])
KeyError: 'name'

ERROR: %s %s %s
[10/10/2008 17:06:19] language
ERROR: %s %s %s
[10/10/2008 17:06:19] color
ERROR: %s %s %s
[10/10/2008 17:06:19] lock
ERROR: %s %s %s
[10/10/2008 17:06:19] width
ERROR: %s %s %s
[10/10/2008 17:06:19] name
ERROR: GET /user/jlopez/preferences jlopez
[10/10/2008 17:06:52] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 105, in read
    create_platform_preferences(user) # Create all platform preferences for the user (if not exist)
  File "/home/juanjo/ezweb/preferences/views.py", line 97, in create_platform_preferences
    preference = Preference.objects.get(user=user, preferenceDef=preferenceDef['pk'])
  File "/var/lib/python-support/python2.5/django/db/models/manager.py", line 93, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 298, in get
    num = len(clone)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 154, in __len__
    self._result_cache = list(self.iterator())
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 269, in iterator
    for row in self.query.results_iter():
  File "/var/lib/python-support/python2.5/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/lib/python-support/python2.5/django/db/models/sql/query.py", line 1700, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/python-support/python2.5/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/var/lib/python-support/python2.5/django/db/backends/mysql/base.py", line 83, in execute
    return self.cursor.execute(query, args)
  File "/var/lib/python-support/python2.5/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/var/lib/python-support/python2.5/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'pk\': "\'language\'", \'model\': "\'preferences.preferencedef\'", \'fields\': {\'defaultV\' at line 1')

ERROR: %s %s %s
[10/10/2008 17:07:33] language
ERROR: GET /user/hola/preferences hola
[10/10/2008 17:07:33] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 106, in read
    preferences = Preference.objects.filter(user=user)
  File "/home/juanjo/ezweb/preferences/views.py", line 98, in create_platform_preferences
    except Preference.DoesNotExist:
KeyError: 'name'

ERROR: %s %s %s
[10/10/2008 17:07:39] pk
ERROR: GET /user/hola/preferences hola
[10/10/2008 17:07:39] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 106, in read
    preferences = Preference.objects.filter(user=user)
  File "/home/juanjo/ezweb/preferences/views.py", line 98, in create_platform_preferences
    except Preference.DoesNotExist:
KeyError: 'name'

ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:09:33] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:09:40] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:09:46] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:09:53] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:10:04] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:10:17] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:10:51] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:11:03] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:11:40] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:11:47] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:12:11] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 13:12:18] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:24:50] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:25:05] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:26:22] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:28:13] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:36:15] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:36:20] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:36:31] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:36:37] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:36:43] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:36:51] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:37:04] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:56:56] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:57:05] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 14:57:13] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 15:01:25] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 15:23:39] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 15:29:55] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: PUT /user/admin/preferences admin
[16/10/2008 15:30:37] Platform Preferences cannot be updated: Unterminated string starting at: line 1 column 10 (char 10)
ERROR: GET /user/a/preferences a
[16/10/2008 16:54:24] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 107, in read
    data = serializers.serialize('python', preferences, ensure_ascii=False)
  File "/var/lib/python-support/python2.5/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/var/lib/python-support/python2.5/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/var/lib/python-support/python2.5/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 303, in get
    % self.model._meta.object_name)
DoesNotExist: PreferenceDef matching query does not exist.

ERROR: GET /user/a/preferences a
[16/10/2008 16:54:29] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 107, in read
    data = serializers.serialize('python', preferences, ensure_ascii=False)
  File "/var/lib/python-support/python2.5/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/var/lib/python-support/python2.5/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/var/lib/python-support/python2.5/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 303, in get
    % self.model._meta.object_name)
DoesNotExist: PreferenceDef matching query does not exist.

ERROR: GET /user/a/preferences a
[16/10/2008 16:54:46] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 107, in read
    data = serializers.serialize('python', preferences, ensure_ascii=False)
  File "/var/lib/python-support/python2.5/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/var/lib/python-support/python2.5/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/var/lib/python-support/python2.5/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 303, in get
    % self.model._meta.object_name)
DoesNotExist: PreferenceDef matching query does not exist.

ERROR: GET /user/a/preferences a
[16/10/2008 16:54:50] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 107, in read
    data = serializers.serialize('python', preferences, ensure_ascii=False)
  File "/var/lib/python-support/python2.5/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/var/lib/python-support/python2.5/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/var/lib/python-support/python2.5/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 303, in get
    % self.model._meta.object_name)
DoesNotExist: PreferenceDef matching query does not exist.

ERROR: GET /user/admin/preferences admin
[16/10/2008 16:55:06] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 107, in read
    data = serializers.serialize('python', preferences, ensure_ascii=False)
  File "/var/lib/python-support/python2.5/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/var/lib/python-support/python2.5/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/var/lib/python-support/python2.5/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 303, in get
    % self.model._meta.object_name)
DoesNotExist: PreferenceDef matching query does not exist.

ERROR: GET /user/admin/preferences admin
[16/10/2008 16:57:02] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/juanjo/ezweb/preferences/views.py", line 107, in read
    data = serializers.serialize('python', preferences, ensure_ascii=False)
  File "/var/lib/python-support/python2.5/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/var/lib/python-support/python2.5/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/var/lib/python-support/python2.5/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/var/lib/python-support/python2.5/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 303, in get
    % self.model._meta.object_name)
DoesNotExist: PreferenceDef matching query does not exist.

ERROR: PUT /workspace/1/variables [Anónimo]
[16/10/2008 18:18:07] Traceback (most recent call last):
  File "/home/juanjo/ezweb/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/juanjo/ezweb/commons/resource.py", line 109, in dispatch
    return target.update(request, *args, **kwargs)
  File "/var/lib/python-support/python2.5/django/db/transaction.py", line 238, in _commit_on_success
    res = func(*args, **kw)
  File "/home/juanjo/ezweb/workspace/views.py", line 424, in update
    user = get_user_authentication(request)
  File "/home/juanjo/ezweb/commons/authentication.py", line 57, in get_user_authentication
    raise Http403 (_("You must be logged"))
Http403: Debe registrarse

